//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangInformModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LangLearnDataEntities : DbContext
    {
        public LangLearnDataEntities()
            : base("name=LangLearnDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<language> languages { get; set; }
        public DbSet<lesson> lessons { get; set; }
        public DbSet<level> levels { get; set; }
        public DbSet<scene> scenes { get; set; }
        public DbSet<sceneitem> sceneitems { get; set; }
        public DbSet<unit> units { get; set; }
        public DbSet<vocabulary> vocabularies { get; set; }
        public DbSet<word> words { get; set; }
        public DbSet<myitem> myitems { get; set; }
    }
}
