//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangInformModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vocabulary
    {
        public vocabulary()
        {
            this.words = new HashSet<word>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IdLesson { get; set; }
    
        public virtual lesson lesson { get; set; }
        public virtual ICollection<word> words { get; set; }
    }
}
