
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixDataTests;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entFileName;
	private global::Gtk.Label lblResult;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label lblStatus;
	private global::Gtk.Image imgPicture;
	private global::Gtk.Button btnStore;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Button btnSoundTests;
	private global::Gtk.Entry entID;
	private global::Gtk.Label label2;
	private global::Gtk.Button btnGetImage;
	private global::Gtk.HSeparator hseparator2;
	private global::Gtk.Label label3;
	private global::Gtk.Button button1;
	private global::Gtk.Entry entWord;
	private global::Gtk.Button btnDialogTest;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 200;
		this.HeightRequest = 200;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixDataTests = new global::Gtk.Fixed ();
		this.fixDataTests.Name = "fixDataTests";
		this.fixDataTests.HasWindow = false;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Image path + filename");
		this.fixDataTests.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.label1]));
		w1.X = 15;
		w1.Y = 16;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.entFileName = new global::Gtk.Entry ();
		this.entFileName.CanFocus = true;
		this.entFileName.Name = "entFileName";
		this.entFileName.IsEditable = true;
		this.entFileName.InvisibleChar = '●';
		this.fixDataTests.Add (this.entFileName);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.entFileName]));
		w2.X = 13;
		w2.Y = 36;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.lblResult = new global::Gtk.Label ();
		this.lblResult.WidthRequest = 30;
		this.lblResult.Name = "lblResult";
		this.fixDataTests.Add (this.lblResult);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.lblResult]));
		w3.X = 131;
		w3.Y = 113;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Image ID: ");
		this.fixDataTests.Add (this.label4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.label4]));
		w4.X = 23;
		w4.Y = 109;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Insert status:");
		this.fixDataTests.Add (this.label5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.label5]));
		w5.X = 24;
		w5.Y = 135;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.lblStatus = new global::Gtk.Label ();
		this.lblStatus.Name = "lblStatus";
		this.fixDataTests.Add (this.lblStatus);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.lblStatus]));
		w6.X = 117;
		w6.Y = 135;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.imgPicture = new global::Gtk.Image ();
		this.imgPicture.WidthRequest = 200;
		this.imgPicture.HeightRequest = 200;
		this.imgPicture.Name = "imgPicture";
		this.fixDataTests.Add (this.imgPicture);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.imgPicture]));
		w7.X = 215;
		w7.Y = 25;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.btnStore = new global::Gtk.Button ();
		this.btnStore.CanFocus = true;
		this.btnStore.Name = "btnStore";
		this.btnStore.UseUnderline = true;
		this.btnStore.Label = global::Mono.Unix.Catalog.GetString ("Store image in database");
		this.fixDataTests.Add (this.btnStore);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.btnStore]));
		w8.X = 29;
		w8.Y = 67;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.WidthRequest = 150;
		this.hseparator1.Name = "hseparator1";
		this.fixDataTests.Add (this.hseparator1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.hseparator1]));
		w9.X = 22;
		w9.Y = 163;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.btnSoundTests = new global::Gtk.Button ();
		this.btnSoundTests.CanFocus = true;
		this.btnSoundTests.Name = "btnSoundTests";
		this.btnSoundTests.UseUnderline = true;
		this.btnSoundTests.Label = global::Mono.Unix.Catalog.GetString ("Sound Tests");
		this.fixDataTests.Add (this.btnSoundTests);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.btnSoundTests]));
		w10.X = 372;
		w10.Y = 285;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.entID = new global::Gtk.Entry ();
		this.entID.WidthRequest = 30;
		this.entID.CanFocus = true;
		this.entID.Name = "entID";
		this.entID.IsEditable = true;
		this.entID.InvisibleChar = '●';
		this.fixDataTests.Add (this.entID);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.entID]));
		w11.X = 131;
		w11.Y = 173;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Image ID:");
		this.fixDataTests.Add (this.label2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.label2]));
		w12.X = 29;
		w12.Y = 176;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.btnGetImage = new global::Gtk.Button ();
		this.btnGetImage.CanFocus = true;
		this.btnGetImage.Name = "btnGetImage";
		this.btnGetImage.UseUnderline = true;
		this.btnGetImage.Label = global::Mono.Unix.Catalog.GetString ("Get image from dB by Id");
		this.fixDataTests.Add (this.btnGetImage);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.btnGetImage]));
		w13.X = 23;
		w13.Y = 208;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.WidthRequest = 150;
		this.hseparator2.Name = "hseparator2";
		this.fixDataTests.Add (this.hseparator2);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.hseparator2]));
		w14.X = 26;
		w14.Y = 245;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Word");
		this.fixDataTests.Add (this.label3);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.label3]));
		w15.X = 28;
		w15.Y = 259;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Get image from dB by word");
		this.fixDataTests.Add (this.button1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.button1]));
		w16.X = 25;
		w16.Y = 289;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.entWord = new global::Gtk.Entry ();
		this.entWord.WidthRequest = 50;
		this.entWord.CanFocus = true;
		this.entWord.Name = "entWord";
		this.entWord.IsEditable = true;
		this.entWord.InvisibleChar = '●';
		this.fixDataTests.Add (this.entWord);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.entWord]));
		w17.X = 125;
		w17.Y = 255;
		// Container child fixDataTests.Gtk.Fixed+FixedChild
		this.btnDialogTest = new global::Gtk.Button ();
		this.btnDialogTest.CanFocus = true;
		this.btnDialogTest.Name = "btnDialogTest";
		this.btnDialogTest.UseUnderline = true;
		this.btnDialogTest.Label = global::Mono.Unix.Catalog.GetString ("Launch error dialog");
		this.fixDataTests.Add (this.btnDialogTest);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixDataTests [this.btnDialogTest]));
		w18.X = 237;
		w18.Y = 286;
		this.Add (this.fixDataTests);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 474;
		this.DefaultHeight = 376;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fixDataTests.Realized += new global::System.EventHandler (this.OnFixDataTestsRealized);
		this.btnStore.Clicked += new global::System.EventHandler (this.OnBtnStoreClicked);
		this.btnSoundTests.Clicked += new global::System.EventHandler (this.OnBtnSoundTestsClicked);
		this.btnGetImage.Clicked += new global::System.EventHandler (this.OnBtnGetImageClicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.btnDialogTest.Clicked += new global::System.EventHandler (this.OnBtnDialogTestClicked);
	}
}
